### ISSUE TITLE
Standardized metrics

### ISSUE THREAD

**Issue by zloo** [sapcc/arista-eapi-exporter#1]
Hi Bernd,

I would like to take your exporter code as basis for my upgrades - I need to monitor more stats (SFP and BGP). I noticed you use some non-standard metrics outPpsRate, which would be better served by just measuring packets sent and calculating rate() with prometheus.

I can fork this project and make the changes in my fork, but I would much rather standardize the values exported and merge them in your repo. Is this something you are okay with? If so, I'll create a pull request for that.

Thanks,

Stefan

**Comment by BerndKue** [comment]
Hi,

I don’t mind if you change it via PR. We will anyway replace the eapi exporter by the snmp one.
I will just have to change the Grafana board displaying the current metrics.

BR
Bernd

________________________________

**Comment by zloo** [comment]
If you don't plan to maintain and use the exporter, I think it makes more sense to update my fork and mention you as the upstream, because I expect to be using this for a long time (instead of SNMP). Is there any reason why you want to use SNMP instead of eAPI, if you don't mind me asking?

**Comment by BerndKue** [comment]
Hi,

We don’t get all metrics via eapi that we need. SNMP is anyway the preferred way for monitoring of devices.
We might just use the eapi to monitor the response time of the API itself.

BR
Bernd

________________________________

**Comment by zloo** [comment]
OK, cool, thanks
